### ISSUE TITLE
Should DurabilityMajority fail on a single node cluster?

### ISSUE THREAD

**Issue by brett19** [couchbase/protostellar#47]
Currently this leads to DurabilityImpossible, but it's possible that it might be better to allow the operation to succeed.

**Comment by brett19** [comment]
Currently it seems like C++ succeeds, but other SDKs generate DurabilityImpossible.

**Comment by avsej** [comment]
@DemetrisChr checked C++ through Ruby, and also said that Java raises exception as well.

**Comment by DemetrisChr** [comment]
I've had a look on wireshark. With the C++ wrappers, the durability requirement is not passed on to the server, which is why the operation succeeds. With Java and the C++ SDK itself, the durability requirement is in the request and the server responds with the status: "The specified durability requirements are not currently possible (0x00a1)"

**Comment by Matt-Woz** [comment]
I tested with Node, which seems to be an exception to the wrappers - it also fails with DurabilityImpossible when run against a single node cluster.

**Comment by DemetrisChr** [comment]
On the topic of the issue, I think it should fail. That seems to be the standard practice across the SDKs. Ruby and PHP were the outliers because of separate bugs that have now both been patched. There is a [requirement](https://docs.couchbase.com/server/current/learn/data/durability.html#majority) on the minimum number of nodes depending on how many replicas there are, so if the requirement is not satisfied, I think it makes sense to fail when you get the relevant status from the server

**Comment by DemetrisChr** [comment]
Yes, operations are indeed successful when that's the case (when replica count is 0). The DurabilityImpossible error comes up when you have a single node and a bucket with a replica count greater than 0, which doesn't sound like a very sensible configuration, but it's possible

**Comment by brett19** [comment]
Ahhh.  This seems like me miss-understanding the original bug.  I was under the impression that Sergey was indicating that this was occurring when ReplicaCount was 0.  It's definitely the case that if your replica-count is >0, and you only have 1 node, that this should "fail" (I quoted "fail" here as it should technically wait until timeout to see if a majority of nodes becomes available).

**Comment by programmatix** [comment]
>  The DurabilityImpossible error comes up when you have a single node and a bucket with replica count greater than 0, which doesn't sound like a very sensible configuration

Unfortunately, this is the default config when creating a new bucket.  It defaults to 1 replica - including on single node clusters.  Users hit this all the time when using transactions.  We had to add a note to the top of the docs (https://docs.couchbase.com/java-sdk/current/howtos/distributed-acid-transactions-from-the-sdk.html)

And yes to confirm what's above:

0 replicas on single node cluster - majority should succeed
1+ replicas on single node cluster - majority should fail with something like DurabilityImpossible

**Comment by brett19** [comment]
I think that everything appears to be working 'as designed', even though the design may be a little annoying for users who are using single-node clusters, but this is probably the 'safest' option anyways.
